version: "3.9"

services:
  muse:
    build: .
    container_name: muse
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network
    env_file:
      - .env.local

networks:
  app-network:
    driver: bridge