services:
  muse:
    build: .
    container_name: muse
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network
    env_file:
      - .env.local

  nginx:
    image: nginx:latest
    container_name: muse-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - muse
    networks:
      - app-network

networks:
  app-network:
    driver: bridge