version: "3.9"

services:
  muse:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: muse-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - muse
    networks:
      - app-network

networks:
  app-network:
    driver: bridge